# Generated by Django 2.1.5 on 2019-01-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedPU',
            fields=[
                ('associateId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('projectId', models.IntegerField(blank=True, null=True)),
                ('statuse', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('feedTime', models.DateTimeField(auto_now=True)),
                ('projectId', models.IntegerField()),
                ('feedComplete', models.TextField(blank=True, null=True)),
                ('feedUnfinished', models.TextField(blank=True, null=True)),
                ('feedConclusion', models.TextField(blank=True, null=True)),
                ('feedProblem', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=255)),
                ('projectStartTime', models.DateTimeField(auto_now=True)),
                ('projectEndTime', models.DateTimeField(auto_now=True)),
                ('projectOnTime', models.DateTimeField(auto_now=True)),
                ('projectSingleId', models.CharField(max_length=255)),
                ('projectFunction', models.TextField(blank=True, null=True)),
                ('projectStatus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('tele', models.CharField(max_length=255)),
                ('superiorIds', models.CharField(blank=True, max_length=255, null=True)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firstapp.User'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firstapp.Project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firstapp.User'),
        ),
        migrations.AddField(
            model_name='associatedpu',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firstapp.Project'),
        ),
        migrations.AddField(
            model_name='associatedpu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Firstapp.User'),
        ),
    ]
