# Generated by Django 2.1.5 on 2019-01-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedpu',
            name='sendUserId',
            field=models.IntegerField(null=True),
        ),
    ]
