# Generated by Django 2.1.5 on 2019-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/201901/21')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('external_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='messageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('context', models.TextField()),
                ('userName', models.CharField(max_length=255)),
                ('acceptPeople', models.TextField()),
                ('acceptPeopleIds', models.TextField()),
            ],
        ),
    ]
