# Generated by Django 2.1.5 on 2019-01-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0002_image_messageinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='messageInfo',
        ),
    ]
