# Generated by Django 2.1.5 on 2019-01-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0002_associatedpu_senduserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sendUserId',
            field=models.IntegerField(null=True),
        ),
    ]
