# Generated by Django 2.1.5 on 2019-01-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0003_feedback_senduserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedpu',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='Firstapp.Project'),
        ),
        migrations.AlterField(
            model_name='associatedpu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='Firstapp.User'),
        ),
    ]
