# Generated by Django 2.1.5 on 2019-01-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0006_auto_20190126_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedSendTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
