# Generated by Django 2.1.5 on 2019-01-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0007_auto_20190128_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedpu',
            name='orderTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
