# Generated by Django 2.1.5 on 2019-01-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0008_associatedpu_ordertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedpu',
            name='orderTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedSendTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
