# Generated by Django 2.1.5 on 2019-01-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0009_auto_20190128_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectEndTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectOnTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectStartTime',
            field=models.DateTimeField(),
        ),
    ]
